---
title: "README"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Template Project

This provides information about R-package for model fitting binding kinetics data using bivalent analyte.

## Folder Structure

The project comprises of two main folders:

### data/

This folder should contain two important files:

- **<...> - info sheet.csv**: this csv file is an info sheet file that has the information about the data sets.
- **<...> - new output format.xlsx**: this xlsx file is an output file has the Time and Response Unit data values.

### code/

This folder should contain `.R` files and subfolders

In this folder:

- **helper_functions.R** contains most of the non-ODE related functions for data processing, data plotting.
- **ode_functions.R** contains ODE-related functions for solving the bivalent analyte model and plotting the results.
- **main.R** is the main script to run bivalent analyte fitting.
- **fitting_results/** is the folder that contains fitting result files (`.Rdata`).
- **figures/** contains the figure files

## Guide 

### Start guide

To start the bivalent analyte model fitting:

1. Make sure your info sheet and output files have the same format as the provided example files. 
2. Run the script **main.R**.
3. The script will ask to set the working directory. Choose the **code/** as your working directory.
4. The script will ask for the info sheet file.
5. The script will ask for the output file.

### Results

After fitting running,

1. The fitting results are saved in an `.Rdata` file within **fitting_results/**.
2. The fitting figures and sensorgrams are saved in **figures/bivalent/**.

### Trouble shooting

The required formatting for this package is not the same as other packages. If you run into problems,

1. In the info sheet file (.csv), make sure the numbers in `Block/Chip/Tray` are separated by semicolon (`;`).
2. In the output file (.xlsx), make sure there are 3 header rows.
3. In the info sheet file (.csv), make sure you have two columns `Sec. Rebinding` and `Model`. 
  - `Sec. Rebinding`: we could assume that the second arms cannot rebind during dissociation phase (`Sec. Rebinding = N`). However, we could also assume that the second arms can rebind during dissociation phase (`Sec. Rebinding = Y`). This is up to the user to decide, however, the default option is `Sec. Rebinding = Y`.
  - `Model`: this version only contains bivalent analyte model, so please set `Model = bivalentAnalyte`. 
